<?php

/**
 * Implements hook_imagemagick_arguments_alter().
 */
function MYMODULE_imagemagick_arguments_alter(\Drupal\imagemagick\ImagemagickExecArguments $arguments, $command) {
  # https://developers.google.com/speed/docs/insights/OptimizeImages
  $arguments->addArgument('-sampling-factor 4:2:0');
  # Progression JPEG and interlaced PNG's support.
  $arguments->addArgument('-interlace Plane');
  # Clean image for all unused data. EXIF etcetera.
  $arguments->addArgument('-strip');
}